name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize, labeled]
    # paths:
    #   - "!*.md"

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.18.0

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: make build

  build_docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25

    - name: Inspect builder
      run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
    - name: Cache image build
      id: cache-image
      uses: actions/cache@v3
      with:
        path: .docker-cache
        key: ${{ runner.os }}-docker-cache

    - name: Buildx
      run: docker buildx bake
